services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: neoarch_test_php
    env_file:
      - test.env
    volumes:
      - ./public:/var/www/html/public:ro
      - ./routes:/var/www/html/routes:ro
      - ./src:/var/www/src:ro
      - ./app-test/mirrors:/var/mirrors:rw
      - ./app-test/gnupg:/srv/http/.gnupg:rw
    restart: unless-stopped
    networks:
      - neoarch-test
    user: "0:0"

  nginx:
    image: nginx:stable-alpine
    container_name: neoarch_test_nginx
    depends_on:
      - php
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
      - ./routes:/var/www/html/routes:ro
      - ./src:/var/www/src:ro
      - ./app-test/ssl:/etc/nginx/ssl:ro
      - ./app-test/logs/nginx:/var/log/nginx:rw
      - ./app-test/mirrors:/var/mirrors:ro
      - ./app-test/isos:/app/isos:ro
    restart: unless-stopped
    networks:
      - neoarch-test

  postgres:
    image: postgres:18-alpine
    container_name: neoarch_test_postgres
    environment:
      POSTGRES_DB: neoarch_test
      POSTGRES_USER: neoarch_test
      POSTGRES_PASSWORD: testpassword
    volumes:
      - ./app-test/db_data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      - neoarch-test

  package-updater:
    build:
      context: .
      dockerfile: docker/package-updater.Dockerfile
    container_name: neoarch_test_package_updater
    env_file:
      - test.env
    depends_on:
      - postgres
    volumes:
      - ./app-test/logs/package-updater:/var/log/package-updater:rw
    restart: unless-stopped
    networks:
      - neoarch-test

  iso-builder:
    build:
      context: .
      dockerfile: docker/iso-builder.Dockerfile
    container_name: neoarch_test_iso_builder
    volumes:
      - ./app-test/isos:/app/isos:rw
    restart: unless-stopped
    networks:
      - neoarch-test
    privileged: true

networks:
  neoarch-test:
    driver: bridge
